<?php

define("FORMBUILDER_UPLOAD_BASE_PATH", "/opt/pij/shared/upload/Formbuilder");

/**
 * Utility class for logic shared between Formbuilder and other apps that wish
 * to interact with Formbuilder.
 *
 * @package default
 * */
class FormbuilderUploadUtil {

    /**
     * Generate the full, file-system path to an upload.
     *
     * FormbuilderUploadUtil::generate_file_upload_path().
     *
     * system.
     *
     * @param string  $path The short path, generated by
     * @return string The full path. Will return null if the file doesn't exist on the current
     * */
    public static function full_file_path($path) {
        $full_path = FORMBUILDER_UPLOAD_BASE_PATH . "/$path";

        // Does the file exist? If not, return null.
        if (!file_exists($full_path) || is_dir($full_path)) {
            return null;
        }

        return $full_path;
    }


    /**
     * Is the given upload an image?
     *
     * FormbuilderUploadUtil::generate_file_upload_path().
     *
     * @param string  $path The short path of the file, as generated bys
     * @return boolean Will return null if the file doesn't exist.
     * */
    public static function is_uploaded_image($path) {
        $path = FormbuilderUploadUtil::full_file_path($path);

        // If the file doesn't exist, return null.
        if ($path === null) {
            return null;
        }

        $stats = getimagesize($path);

        // File wasn't determined to be an image.
        if ($stats === false) {
            return false;
        }
        // We got some valid image stats, so return true.
        else {
            return true;
        }
    }


    /**
     * Generate a relative path to use for a form-related file upload.
     *
     * @param unknown $ask_id
     * @param unknown $askq_id
     * @param unknown $ask_title
     * @param unknown $askq_text
     * @param unknown $proj_name
     * @return void
     * */
    public static function generate_file_upload_path(
        $ask_id,
        $askq_id,
        $ask_title,
        $askq_text,
        $proj_name
    ) {
        $path = "";

        if (empty($askq_id)) {
            return $path;
        }

        if (!empty($proj_name) && !empty($ask_id)) {
            $path .= strtolower(preg_replace("/[^\w\.]/", "_", $proj_name)) .
                "/" . strtolower(preg_replace("/[^\w\.]/", "_", substr($ask_title, 0, 20))) .
                "_" . $ask_id .
                "/" . strtolower(preg_replace("/[^\w\.]/", "_", substr($askq_text, 0, 20))) .
                "_" . $askq_id;

        }

        return $path;
    }


}
